services:
  app:
    build: .
    container_name: fastapi-container
    command: uvicorn src.main:app --host 0.0.0.0 --port 8000 --reload
    ports:
      - 8000:8000
    volumes:
      - .:/code
    depends_on:
      - redis

  redis:
    image: redis:alpine